server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: getway-9527
    prefer-ip-address: true
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
# 忽略所有的服务路由，只使用代理路由
  ignored-services: "*"
# 代理的前缀，原访问录取前加/wjy
  prefix: /wjy